version: "3.5"

x-common-variables: &common-variables
  KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
  KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:SASL_SSL,BROKER:SASL_SSL,EXTERNAL:SASL_SSL
  KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  KAFKA_PROCESS_ROLES: 'controller,broker'
  CLUSTER_ID: 'YDUtH4RNTJSLYDHLP489Yg'
  KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9091,2@kafka2:9091,3@kafka3:9091'
  KAFKA_METADATA_LOG_SEGMENT_MS: 15000
  KAFKA_METADATA_MAX_RETENTION_MS: 1200000
  KAFKA_METADATA_LOG_MAX_RECORD_BYTES_BETWEEN_SNAPSHOTS: 2800
  KAFKA_LOG_DIRS: '/var/lib/kafka/data'
  KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
  KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
  KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
  KAFKA_SUPER_USERS: User:admin
  KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
  KAFKA_AUTHORIZER_CLASS_NAME: "org.apache.kafka.metadata.authorizer.StandardAuthorizer"
  KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/jaas.conf"
  KAFKA_LOG4J_LOGGERS: "kafka.authorizer.logger=DEBUG"
  KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
  KAFKA_SECURITY_PROTOCOL: SSL
  KAFKA_SSL_CLIENT_AUTH: requested
  KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/kafka.broker.keystore.jks
  KAFKA_SSL_KEYSTORE_PASSWORD: "changeit"
  KAFKA_SSL_KEY_PASSWORD: "changeit"
  KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/kafka.broker.truststore.jks
  KAFKA_SSL_TRUSTSTORE_PASSWORD: "changeit"
  KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''

services:
  kafdrop:
    image: obsidiandynamics/kafdrop:4.0.1
    hostname: kafdrop
    container_name: kafdrop
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka1:9092,kafka2:9092,kafka3:9092
      KAFKA_PROPERTIES_FILE: /client.admin.properties
      JVM_OPTS: "-Xms128M -Xmx512M -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    volumes:
      - ./client.admin.properties:/client.admin.properties
      - ./ssl/kafdrop.keystore.jks:/kafka.keystore.jks
      - ./ssl/kafdrop.truststore.jks:/kafka.truststore.jks

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.1
    hostname: kafka-ui
    container_name: kafka-ui
    ports:
      - 8080:8080
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    environment:
      KAFKA_CLUSTERS_0_NAME: home
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092,kafka2:9092,kafka3:9092
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_SSL
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="adminPa%3";'
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_LOCATION: /kafka.keystore.jks
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_PASSWORD: "changeit"
      KAFKA_CLUSTERS_0_SSL_TRUSTSTORELOCATION: /kafka.truststore.jks
      KAFKA_CLUSTERS_0_SSL_TRUSTSTOREPASSWORD: "changeit"
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''
    volumes:
      - ./ssl/kafka-ui.keystore.jks:/kafka.keystore.jks
      - ./ssl/kafka-ui.truststore.jks:/kafka.truststore.jks

  kafka1:
    image: confluentinc/cp-kafka:7.5.3
    hostname: kafka1
    container_name: kafka1
    ports:
      - 39091:39091
    environment:
      <<: *common-variables
      KAFKA_LISTENERS: CONTROLLER://kafka1:9091,BROKER://kafka1:9092,EXTERNAL://kafka1:39091
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka1:9092,EXTERNAL://kafka1:39091
      KAFKA_NODE_ID: 1
    volumes:
      - kafka1-data:/var/lib/kafka/data
      - ./kafka.jaas.conf:/etc/kafka/jaas.conf
      - ./ssl/kafka1.keystore.jks:/etc/kafka/kafka.broker.keystore.jks
      - ./ssl/kafka1.truststore.jks:/etc/kafka/kafka.broker.truststore.jks

  kafka2:
    image: confluentinc/cp-kafka:7.5.3
    hostname: kafka2
    container_name: kafka2
    ports:
      - 39092:39092
    environment:
      <<: *common-variables
      KAFKA_LISTENERS: CONTROLLER://kafka2:9091,BROKER://kafka2:9092,EXTERNAL://kafka2:39092
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka2:9092,EXTERNAL://kafka2:39092
      KAFKA_NODE_ID: 2
    volumes:
      - kafka2-data:/var/lib/kafka/data
      - ./kafka.jaas.conf:/etc/kafka/jaas.conf
      - ./ssl/kafka2.keystore.jks:/etc/kafka/kafka.broker.keystore.jks
      - ./ssl/kafka2.truststore.jks:/etc/kafka/kafka.broker.truststore.jks

  kafka3:
    image: confluentinc/cp-kafka:7.5.3
    hostname: kafka3
    container_name: kafka3
    ports:
      - 39093:39093
    environment:
      <<: *common-variables
      KAFKA_LISTENERS: CONTROLLER://kafka3:9091,BROKER://kafka3:9092,EXTERNAL://kafka3:39093
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka3:9092,EXTERNAL://kafka3:39093
      KAFKA_NODE_ID: 3
    volumes:
      - kafka3-data:/var/lib/kafka/data
      - ./kafka.jaas.conf:/etc/kafka/jaas.conf
      - ./ssl/kafka3.keystore.jks:/etc/kafka/kafka.broker.keystore.jks
      - ./ssl/kafka3.truststore.jks:/etc/kafka/kafka.broker.truststore.jks
volumes:
  kafka1-data:
  kafka2-data:
  kafka3-data:
